homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

story4/urls.py
from django.urls import path, include
from django.contrib import admin
from jadwal.views import buat_jadwal, list_jadwal, delete

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('jadwal/', list_jadwal, name='list_jadwal'),
    path('form/', buat_jadwal, name='buat_jadwal'),
    path('jadwal/<int:delete_id>/delete', delete, name='delete')
]

homepage/models.py
from django.db import models

# Create your models here.

jadwal/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
    LIST_KATEGORI = (
        ('Hiburan', 'Hiburan'),
        ('Tugas', 'Tugas'),
        ('Kelas', 'Kelas'),
        ('Lain-lain', 'Lain-lain')
    )
    kategori = models.CharField(max_length=30, choices=LIST_KATEGORI)
    name = models.CharField(max_length=30)
    place = models.CharField(max_length=30)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

jadwal/forms.py
from django import forms
from .models import Jadwal
from bootstrap_datepicker_plus import DateTimePickerInput

class JadwalForm(forms.ModelForm):
    class Meta:
        model = Jadwal
        fields = [
            'kategori',
            'name',
            'place',
            'start_time',
            'end_time',
        ]

        labels = {
            'kategori':'Kategori',
            'name':'Kegiatan',
            'place':'Tempat',
            'start_time':'Waktu mulai',
            'end_time':'Waktu berakhir',
        }

        widgets = {
            'kategori': forms.Select(
                attrs={
                    'class': 'form-control',
                },
            ),
            'name':forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Masukkan nama kegiatan anda',
                },
            ),
            'place': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Masukkan tempat kegiatan anda',
                },
            ),
            'start_time':DateTimePickerInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'yyyy/mm/dd HH:MM'
                },
            ),
            'end_time':DateTimePickerInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'yyyy/mm/dd HH:MM'
                },
            ),
        }

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def contact(request):
    return render(request, 'contact.html')

def about(request):
    return render(request, 'about.html')

jadwal/views.py
from django.shortcuts import render, redirect
from .forms import JadwalForm
from .models import Jadwal
# Create your views here.

def buat_jadwal(request):
    form = JadwalForm(request.POST or None)
    if form.is_valid():
        form.save()
        # form = JadwalForm()
        return redirect('list_jadwal')  

    context = {
        'form':form
    }

    return render(request, 'jadwal/buat_jadwal.html', context)

def list_jadwal(request):
    obj = Jadwal.objects.all()

    context = {
        'jadwals':obj
    }

    return render(request, 'jadwal/list_jadwal.html', context)

def delete(request, delete_id):
    Jadwal.objects.filter(id=delete_id).delete()
    return redirect('list_jadwal')

homepage/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>McDy PPW ABOUT</title>
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  	 	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<link href="{% static 'css/main.css' %}" rel="stylesheet">
    </head>
    <body class="page2">
        <nav class="navbar navbar-expand-md bg-dark navbar-dark">
            <a class="navbar-brand" href="#">DahlanYasa</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'list_jadwal' %}">Kegiatan</a>
                    </li>
                </ul>
            </div>  
        </nav>

        <div class="profile container" id="profile">
            <div class="profile-header">
                <h1 class="text-center"><b>ABOUT</b></h1>
                <h2 class="text-center">Let me introduce myself</h2>
                <hr class='header-line'>
            </div>
            <div class="container">
                <div class="row">
                    <div class="foto-container">
                        <img src="{% static 'images/01Dahlan.png' %}" class="rounded-circle my-poto" alt="Pas-Foto">
                        <p class="text-justify about-me font-profile">I’m an ambitious junior prorammer student striving for computing knowledge. I am interested in  Web Development, Machine Learning, and Game Development. I am determined and passionate when it comes to my interests, especially if it helps other people and make the world a better place.</p>
                    </div>
                </div>
            </div>
            <div class="about-content">
                <h1>Profile</h1>
                <ul class="infolist">
                    <li>
                        <strong>Fullname: </strong>
                        <span>Muhammad Dahlan Yasadipura</span>
                    </li>
                    <li>
                        <strong>Birth Date: </strong>
                        <span>May 8, 2000</span>
                    </li>
                    <li>
                        <strong>website: </strong>
                        <span>DahlanYasa.herokuapp.com</span>
                    </li>
                    <li>
                        <strong>Contact: </strong>
                        <span>mdahlany@gmail.com</span>
                    </li>
                </ul>
            </div>

        </div>
    </body>
</html>

homepage/templates/contact.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>McDy PPW ABOUT</title>
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  	 	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<link href="{% static 'css/main.css' %}" rel="stylesheet">
    </head>
    <body class="page3">
        <nav class="navbar navbar-expand-md bg-dark navbar-dark">
            <a class="navbar-brand" href="#">DahlanYasa</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'list_jadwal' %}">Kegiatan</a>
                    </li>    
                </ul>
            </div>  
        </nav>
        <div class="contactPage">
            <h5>CONTACT ME</h5>
            <div class="baris">
                <a href="http://line.me/ti/p/~dahlany">
                <img id="line" src="{% static 'images/87386.png' %}">
                </a>
                <a href="https://www.facebook.com/mdahlan.ganteng">
                <img id="facebook" src="{% static 'images/697057-facebook-512.png'%}">
                </a>
                <a href="">
                <img id="whatsapp" src="{% static 'images/whatsapp-icon-logo-6E793ACECD-seeklogo.com.png'%}">
                </a>
                <a href="https://www.linkedin.com/in/muhammad-dahlan-yasadipura-94b440126?originalSubdomain=id">
                <img id="linkedin" src="{% static 'images/linkedin-icon-png-transparent-background-13.png'%}">
                </a>
            </div>
        </div>
    </body>
</html>

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>McDy PPW</title>
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  	 	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<link href="{% static 'css/main.css' %}" rel="stylesheet">
	</head>
	<body>
		<nav class="navbar navbar-expand-md bg-dark navbar-dark">
			<a class="navbar-brand" href="#">DahlanYasa</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
					<span class="navbar-toggler-icon"></span>
				</button>
			<div class="collapse navbar-collapse" id="collapsibleNavbar">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'homepage:about' %}">About</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'list_jadwal' %}">Kegiatan</a>
					</li>  
				</ul>
			</div>  
		</nav>
		<div class="landing" id="landing">
			<img name="bg" src="{% static 'images/wp4312249.png'%}">
			<h5>HI...</h5>
			<h1 class="text-center">I'm Muhammad Dahlan Yasadipura</h1>
			<hr class='main-line'>
			<p class="text-center turunin-font-size">
				<span>Software Engineer</span>
				<span>Computer Science Student </span>
			</p>
		</div>
		
	</body>
</html>

jadwal/templates/jadwal/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    {{ form.media }}
    <title>
        {% block page_title %}

        {% endblock page_title %}
    </title>
</head>
<body style="roboto">
    <div>
        <nav class="navbar navbar-expand-md bg-dark navbar-dark">
            <a class="navbar-brand" href="#">DahlanYasa</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'list_jadwal' %}">Jadwal</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'buat_jadwal' %}">Create Jadwal</a>
                    </li>  
                </ul>
            </div>  
        </nav>
    </div>
    
    <div class="container flex-wrap text-center pt-4">
        <div class="resume-header">
        <h1 class="text-center text-info"><b>
            {% block header %}
        
            {% endblock header %}
        </b></h1>
        <hr class='col-xl-11 border border-dark rounded-circle bg-dark'>
    </div>

    </div>
    <div class='container-fluid'>
        {% block content %}

        {% endblock content %}
    </div>

    <!--
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    -->
</body>
</html>

jadwal/templates/jadwal/buat_jadwal.html
{% extends 'jadwal/base.html' %}

{% block page_title %}
    Form Kegiatan
{% endblock page_title %}

{% block header %}
    Form Kegiatan
{% endblock header %}

{% block content %}
<div class='container'>
    <form method='post'>
        {% csrf_token %}
        {% for form in form %}
            <div class='form-group'>
                {{form.label}}
                {{form}}                
            </div>          
        {% endfor %}
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}          
        <br>
        <input type='submit' class='btn btn-primary mb-2 float-right' value='Submit'/>
    </form>
<div>
{% endblock content %}

jadwal/templates/jadwal/list_jadwal.html
{% extends 'jadwal/base.html' %}

{% block page_title %}
    List Kegiatan
{% endblock page_title %}

{% block header %}
    List Kegiatan
{% endblock header %}

{% block content %}
    {% if not jadwals %}
        <div class='d-flex justify-content-center'>
            <p>Mohon maaf, tidak ada Jadwal yang dapat ditampilkan.</p>
        </div>
    {% else %}
        <div class='table-responsive'>
            <table class='table table-striped'>
                <thead class='thead-dark'>
                    <tr>
                        <th scope='col' class='align-middle'>#</th>
                        <th scope='col' class='align-middle'>Kategori</th>
                        <th scope='col' class='align-middle'>Nama Kegiatan</th>
                        <th scope='col' class='align-middle'>Tempat</th>
                        <th scope='col' class='align-middle'>Waktu Mulai</th>
                        <th scope='col' class='align-middle'>Waktu Berakhir</th>
                        <th scope='col' class='align-middle'>Delete</th>
                    <tr>
                </thead>
                <tbody>
                    {% for jadwal in jadwals %}
                        <tr>
                            <th scope='row' class='align-middle'>{{forloop.counter}}</th>
                            <td class='align-middle'>{{jadwal.kategori}}</th>
                            <td class='align-middle'>{{jadwal.name}}</th>
                            <td class='align-middle'>{{jadwal.place}}</th>
                            <td class='align-middle'>{{jadwal.start_time}}</th>
                            <td class='align-middle'>{{jadwal.end_time}}</th>
                            <td class='align-middle'><a class='btn btn-danger' href='{% url 'delete' jadwal.id %}' title=''>Delete</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            <table>
        </div>
    {% endif %}
{% endblock content %}